version: '3.8'

services:
  server: 
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    command: ["./usr/local/bin/desk_server"]
    ports:
      - "50051:50051"
    environment:
      - SERVER_PORT=50051
      - DEBUG=${DEBUG:-false}
    networks:
      - app-network
    restart: unless-stopped
    
    volumes:
      - ./server/src:/app/src
    healthcheck:
      test: ["CMD", "ss", "-l", "-n", "|", "grep", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge