/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Widget" CASCADE;

DROP TABLE IF EXISTS "Board" CASCADE;

DROP TABLE IF EXISTS "User" CASCADE;

CREATE TABLE "User" (
  "uuid" TEXT NOT NULL PRIMARY KEY,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL);

CREATE UNIQUE INDEX "User_username_i"
  ON "User" ("username");

CREATE TABLE "Board" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  CONSTRAINT "owner_fk"
    FOREIGN KEY ("owner")
    REFERENCES "User" ("uuid")
    ON DELETE CASCADE
    INITIALLY DEFERRED);

CREATE UNIQUE INDEX "Board_name_i"
  ON "Board" ("name");

CREATE TABLE "Widget" (
  "id" BIGINT NOT NULL PRIMARY KEY,
  "x_coord" INTEGER NOT NULL,
  "y_coord" INTEGER NOT NULL,
  "content" TEXT NOT NULL,
  "board" BIGINT NOT NULL,
  CONSTRAINT "board_fk"
    FOREIGN KEY ("board")
    REFERENCES "Board" ("id")
    ON DELETE CASCADE
    INITIALLY DEFERRED);

